# Generated by Django 4.0.5 on 2022-06-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
